spotify/ratatool

.gitignore
build.sbt
project/plugins.sbt
src/main/scala/com/spotify/ratatool/generators/TableRowGenerator.scala
src/main/scala/com/spotify/ratatool/io/AvroIO.scala
src/main/scala/com/spotify/ratatool/io/FileStorage.scala
src/main/scala/com/spotify/ratatool/samplers/BigSampler.scala
src/main/scala/com/spotify/ratatool/serde/JsonSerDe.scala
src/test/resources/schema.json
src/test/scala/com/spotify/ratatool/samplers/BigSamplerTest.scala

This it RFC. @nevillelyh @andrewsmartin  (please give feedback when you have some free time).
This is suppose to cover basic use cases of sampling for pipeline testing.
The overall concept would be:
* BigSampler is a "generic enough" sampling job capable of sampling Avro/BigQuery
* sampling happens on user defined key(s) (either via avro-schema or fields specified CLI)
Example of execution:
```
> sbt pack
> ./target/pack/bin/big-sampler --sample=5  --input=<table-reference-inpute> --output=<table-reference-sample> --project=<project> --zone=<zone> --stagingLocation=<staging> --fields=user_id --runner=DataflowPipelineRunner
```
Manual flow for sampling and running a job on sampled data would require to sample on each input, but this process can be automated with orchestrator (example …

wip sample

---

build.sbt
ratatool/src/main/scala/com/spotify/ratatool/diffy/BigDiffy.scala
ratatool/src/main/scala/com/spotify/ratatool/diffy/ProtoBufDiffy.scala
ratatool/src/main/scala/com/spotify/ratatool/generators/ProtoBufGenerator.scala
ratatool/src/main/scala/com/spotify/ratatool/scalacheck/ProtoBufGen.scala

To be compatible with proto 2 and 3 compiled message classes.  Upgrade compiler to v3.3.0
Suggested solution to https://github.com/spotify/ratatool/issues/31.  Maybe it would be better to include implementation for builders and instead change this to `GeneratedMessageV3` for `.asInstanceOf[]` calls?
@idreeskhan

use AbstractMessage: super of GeneratedMessage

---

build.sbt

This changes the GCS batch request endpoint to the new per-api endpoint
(https://github.com/GoogleCloudPlatform/bigdata-interop/blob/branch-1.6.x/gcs/CHANGES.txt),
as the old endpoint is being deprecated
(https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html).

Update GCS connector from 1.6.1 to 1.6.3.

---

ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/BigDiffy.scala

```
numTotal	numSame	numDiff	numMissingLhs	numMissingRhs
215273	0	40	9488	205745
```

BigDiffy output with header

---

ratatool-diffy/diffy.md
ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/BigDiffy.scala
ratatool-sampling/sampler.md
ratatool-sampling/src/main/scala/com/spotify/ratatool/samplers/BigSampler.scala

Add more documentation on Diffy, Sampler usage

---

ratatool-diffy/diffy.md
ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/BigDiffy.scala
ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/Diffy.scala
ratatool-diffy/src/test/scala/com/spotify/ratatool/diffy/BigDiffyTest.scala

#69 Allows user to consume output data for key-level analysis. Also directly puts differences into the output

Change Key Stats to output field level deltas and distances

---

ratatool-sampling/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/PatchedBigQueryServices.java
ratatool-sampling/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/PatchedBigQueryServicesImpl.java
ratatool-sampling/src/main/scala/com/spotify/ratatool/io/BigQueryIO.scala
ratatool-sampling/src/main/scala/com/spotify/ratatool/samplers/BigSampler.scala

This is named the same as `BigQueryServices` which is tries to override. When running packed build the result is that it tries to execute Beams protected class with the same canonical name. This PR avoids that issue.

Rename BigQueryServices to avoid protected error in packed deployment

---

ratatool-scalacheck/README.md
ratatool-scalacheck/src/main/scala/com/spotify/ratatool/scalacheck/package.scala
ratatool-scalacheck/src/test/scala/com/spotify/ratatool/scalacheck/AvroGeneratorTest.scala
ratatool-scalacheck/src/test/scala/com/spotify/ratatool/scalacheck/ProtoBufGeneratorTest.scala
ratatool-scalacheck/src/test/scala/com/spotify/ratatool/scalacheck/TableRowGeneratorTest.scala

Possibly simplifies #81 
This is likely more specifically for joinable data but could theoretically expand API up to Tuple22 if needed. Premise is that for building joinable dataset you build a Gen of tuple and then amend2 over that tuple. This is what I have been doing on my own already and this trims down the necessary work by a bit. Still not ideal but a slight improvement.

Add amend2 for joinable generators

---

ratatool-common/src/main/avro/TestRecord.avsc
ratatool-common/src/main/protobuf/schemas.proto
ratatool-common/src/test/resources/schema.json
ratatool-examples/src/main/scala/com/spotify/ratatool/examples/scalacheck/GenExample.scala
ratatool-scalacheck/src/main/scala/com/spotify/ratatool/scalacheck/package.scala
ratatool-scalacheck/src/test/scala/com/spotify/ratatool/scalacheck/AvroGeneratorTest.scala
ratatool-scalacheck/src/test/scala/com/spotify/ratatool/scalacheck/ProtoBufGeneratorTest.scala
ratatool-scalacheck/src/test/scala/com/spotify/ratatool/scalacheck/TableRowGeneratorTest.scala

This will allow it so multiple functions can be provided to the `amend` functions now
Addresses https://github.com/spotify/ratatool/issues/100

adding in multiple functions

---

build.sbt
ratatool-diffy/README.md
ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/BigDiffy.scala
ratatool-sampling/README.md

Upload diff results from BigDiffy to BigQuery

---

ratatool-shapeless/src/main/scala/com/spotify/ratatool/shapeless/CaseClassDiffy.scala

A patch for #105 (issue #122). The trait has to be serialisable to be sent over the network.

Make CaseClassDiffy's MapEncoder trait serializable

---

ratatool-sampling/src/main/scala/com/spotify/ratatool/samplers/BigSampler.scala
ratatool-sampling/src/main/scala/com/spotify/ratatool/samplers/util/SamplerSCollectionFunctions.scala
ratatool-sampling/src/main/scala/com/spotify/scio/Random.scala

Fix Serialization issue as well as min/max bound for uniform sampling

---

ratatool-sampling/src/main/scala/com/spotify/ratatool/samplers/BigSampler.scala
ratatool-sampling/src/test/scala/com/spotify/ratatool/samplers/BigSamplerTest.scala

The current implementation of sample fraction takes too many samples when the fraction <= 0.01.

Fixes sample fraction logic

---

ratatool-cli/src/main/scala/com/spotify/ratatool/tool/Ratatool.scala
ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/BigDiffy.scala
ratatool-sampling/src/main/java/com/spotify/ratatool/GcsConfiguration.java
ratatool-sampling/src/main/scala/com/spotify/ratatool/samplers/AvroSampler.scala
ratatool-sampling/src/test/scala/com/spotify/ratatool/samplers/AvroSamplerTest.scala

Move Avro sampler to FileSystems API

---

ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/BigDiffy.scala
ratatool-diffy/src/test/scala/com/spotify/ratatool/diffy/BigDiffyTest.scala
ratatool-examples/src/main/scala/com/spotify/ratatool/examples/diffy/PreProcessBigDiffy.scala
ratatool-examples/src/main/scala/com/spotify/ratatool/examples/diffy/ProtobufBigDiffyExample.scala
ratatool-shapeless/src/main/scala/com/spotify/ratatool/shapeless/CaseClassDiffy.scala

Addresses #137.
There were two options that I thought about:
1) Join all keys and to get a single String in `*KeyFn` functions.
2) Use the list of string representation of the keys as key to the join.
Decided to go with (1) since we will need to join the keys anyways to write the results.

Support multiple keys in bigdiffy

---

ratatool-diffy/README.md
ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/BigDiffy.scala
ratatool-sampling/README.md
ratatool-sampling/src/main/scala/com/spotify/ratatool/samplers/BigSampler.scala

Nothing else stood out to me in the Dataflow 2 migration guide but if you want you can double check it at https://cloud.google.com/dataflow/docs/guides/migrate-java-1-to-2

update READMEs and docs to provide correct tempLocation info for Dataflow 2.x

---

ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/AvroDiffy.scala
ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/BigDiffy.scala
ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/Diffy.scala
ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/ProtoBufDiffy.scala
ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/TableRowDiffy.scala
ratatool-diffy/src/test/scala/com/spotify/ratatool/diffy/AvroDiffyTest.scala
ratatool-diffy/src/test/scala/com/spotify/ratatool/diffy/BigDiffyTest.scala
ratatool-diffy/src/test/scala/com/spotify/ratatool/diffy/ProtoBufDiffyTest.scala
ratatool-diffy/src/test/scala/com/spotify/ratatool/diffy/TableRowDiffyTest.scala
ratatool-shapeless/src/main/scala/com/spotify/ratatool/shapeless/CaseClassDiffy.scala
ratatool-shapeless/src/test/scala/com/spotify/ratatool/shapeless/CaseClassDiffyTest.scala

Change Delta case class to store LHS and RHS as Options, so we're not shuffling around and eventually saving a null value when one half of the diff is null
This solves an NPE which occurs in Dataflow when diffing two fields, one of which is null and one of which isn't. The NPE occurs at the end of the pipeline, when trying to write diff results to BigQuery. The exception's trace contains `Caused by: org.apache.beam.sdk.coders.CoderException: cannot encode a null value`. 
Fixes https://github.com/spotify/ratatool/issues/152

BigDiffy: Delta is serialized, shouldn't contain nulls

---

build.sbt
project/plugins.sbt

We already had this dependency (see https://github.com/spotify/ratatool/blob/master/ratatool-scalacheck/src/main/scala/com/spotify/ratatool/scalacheck/ProtoBufGenerator.scala#L23) and it wasn't declared, causing trouble for downstreams that didn't already depend on Guava. 
Also added a plugin to visualize dependencies :)
Fixes https://github.com/spotify/ratatool/issues/153

Add previously-undeclared dependency on Guava

---

ratatool-common/src/test/resources/EvolvedSimpleRecord.avsc
ratatool-common/src/test/resources/SimpleRecord.avsc
ratatool-common/src/test/scala/com/spotify/ratatool/Schemas.scala
ratatool-diffy/README.md
ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/AvroDiffy.scala
ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/BigDiffy.scala
ratatool-diffy/src/test/scala/com/spotify/ratatool/diffy/AvroDiffyTest.scala

Related to #146 
This assumes that the RHS schema is the "new" schema (backwards compatible to LHS). I also moved this outside of AvroDiffy.
Need to add some tests and docs but curious to hear thoughts on this

Assert that schema is backwards compatible for Avro

---

ratatool-sampling/src/main/scala/com/spotify/ratatool/samplers/BigSampler.scala
ratatool-sampling/src/main/scala/com/spotify/ratatool/samplers/BigSamplerAvro.scala
ratatool-sampling/src/main/scala/com/spotify/ratatool/samplers/BigSamplerBigQuery.scala
ratatool-sampling/src/test/scala/com/spotify/ratatool/samplers/BigSamplerAvroTest.scala

Fixes https://github.com/spotify/ratatool/issues/157
Neville suggested that we avoid trying to serialize `Object`/`Any`/`AnyRef` because we can't serialize those at compile time. Moving the `Set[Any]` key to a `Set[String]` means that we don't even need the nullableCoders fixes in Scio 0.8.0 for it to work :)

Fix BigSampler NPE

---

ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/BigDiffy.scala
ratatool-diffy/src/test/scala/com/spotify/ratatool/diffy/BigDiffyTest.scala

Comparing datasets which were grouped by compound key might result in one of the keys having `null` value.
Eg: we have a table grouped by `(company, country, product)` for total number of sales. It's possible that one of the products is `null` as there is no single unique key in this table in order to compare two versions I have to create compound key with `--key=company --key=country --key=product` as `product` might be `null` the unpatched version would throw `NullPointerException`:
```
[ForkJoinPool-1-worker-13] ERROR org.apache.beam.runners.dataflow.util.MonitoringUtil$LoggingHandler - 2019-05-17T14:33:47.344Z: java.lang.NullPointerException
at com.spotify.ratatool.diffy.BigDiffy$.com$spotify$ratatool$diffy$BigDiffy$$get$1(BigDiffy.scala:428)
at …
```

Allow bigDiffy to work with nullable keys

---

ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/BigDiffy.scala
ratatool-diffy/src/test/scala/com/spotify/ratatool/diffy/BigDiffyTest.scala

https://github.com/spotify/ratatool/pull/160 allowed for null values in keys.  This adds a warning whenever we encounter a null key.  Also throw an error whenever keys are non-unique as that might be somewhat easier to do by accident for nullable fields now

Warn on null keys

---

ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/BigDiffy.scala
ratatool-diffy/src/test/scala/com/spotify/ratatool/diffy/BigDiffyTest.scala

We received a user report that Ratatool succeeded in running a diff but they didn't know where the result was output to. We should fail fast if the output location is invalid.

add check that GCS output begins with gs://

---

ratatool-common/src/main/avro/TestRecord.avsc

Sometimes these are generated without a namespace
Then, we fail to compile because of this Scala bug: https://github.com/scala/bug/issues/4071?orig=1
We can make sure it gets generated with a namespace by specifying namespace
this is valid avro per https://avro.apache.org/docs/current/spec.html#Enums

Add namespace to TestRecord enum & fixed (fix compile in circleci?)

---

README.md

`input_mode` to `input-mode`
Error messaging should be improved for specific unknown params

Fixes bigDiffy param reference in README

---

README.md
ratatool-common/src/test/resources/SimpleByteFieldRecord.avsc
ratatool-common/src/test/scala/com/spotify/ratatool/Schemas.scala
ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/BigDiffy.scala
ratatool-diffy/src/test/scala/com/spotify/ratatool/diffy/AvroDiffyTest.scala

The default toString for a byte buffer doesn't contain its content,
just metadata that's the same for every byte buffer of the same size.
If you used a bytes field in Avro as your key,
this would cause a hot key of that default string, rather than grouping by key values.
This fix uses the hex version of what's actually inside the buffer.
confirmed with user that diff job succeeds with this change in place

Stringify byte buffers in diffy avro keys

---

build.sbt

It's not published for 2.13. because it has been included in the compiler

only use macro-paradise for scala 2.12

---

build.sbt

fixes: currently unable to release as extras fails to compile locally, maybe this used to be pulled in transitively?
```
[error] /home/anned/spotify-git/ratatool/ratatool-extras/src/main/java/com/spotify/ratatool/GcsConfiguration.java:87:1: cannot access com.google.cloud.hadoop.util.EntriesCredentialConfiguration
[error]   class file for com.google.cloud.hadoop.util.EntriesCredentialConfiguration not found
[error] HadoopCredentialConfiguration.BASE_KEY_PREFIX
[error] /home/anned/spotify-git/ratatool/ratatool-extras/src/main/java/com/spotify/ratatool/GcsConfiguration.java:88:1: cannot find symbol
[error]   symbol:   variable ENABLE_SERVICE_ACCOUNTS_SUFFIX
[error]   location: class com.google.cloud.hadoop.util.HadoopCredentialConfiguration
[error] …
```

fix broken compile on master, & upgrade lib

---

ratatool-scalacheck/README.md

Since [v0.3.1.4](https://github.com/spotify/ratatool/releases/tag/v0.3.14), CaseClassGenerator is no longer in this repository
> CaseClassGenerator has been removed. If this is needed users should migrate to generators in magnolify
Remove related documentation

Update documentation: Case class generators has moved to magnolify

---

ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/BigDiffy.scala
ratatool-diffy/src/test/scala/com/spotify/ratatool/diffy/BigDiffyTest.scala
ratatool-sampling/src/main/scala/com/spotify/ratatool/samplers/BigSampler.scala
ratatool-sampling/src/main/scala/com/spotify/ratatool/samplers/util/SamplerSCollectionFunctions.scala
ratatool-scalacheck/src/test/scala/com/spotify/ratatool/scalacheck/ProtoBufGeneratorTest.scala

Don't know if this is a good idea or not but it was annoying to me to have to import ratatool as a dependency just to use this feature (and therefore commit diff jobs into a pipeline repo). Basically allows `->` demarcated field key mappings for nested records that can be ',' delimited to specify multiple field mappings. Let me know what you think

Fix some warnings and add command line parsing for unordered field keys

---

ratatool-diffy/README.md

a user ran into an avro error diffing two schemas where the rhs one added a non-nullable field. waiting on her to confirm that a backwards-compatible schema works.
this is based on my understanding of the current behavior after reading [AvroDiffy](https://github.com/spotify/ratatool/blob/master/ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/AvroDiffy.scala).
not sure yet if we want to change this behavior.

[WIP] clarify limits of schema evolution

---

ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/BigDiffy.scala

Adds the `convert-nulls` option to convert nulls to "null" for use as keys in BigQuery diffs. This is very useful for comparing output
datasets when `null` is an expected value/category for a string key e.g. in datasets where `null` country codes might be expected for example.
From the code it seems this is already the behaviour in Avro diffs, it is only BQ diffs that would fail previously.

Add option to convert nulls for BQ keys

---

build.sbt
ratatool-scalacheck/README.md
ratatool-scalacheck/src/main/scala/com/spotify/ratatool/scalacheck/GenTestUtils.scala
ratatool-scalacheck/src/test/scala/com/spotify/ratatool/scalacheck/GenTestUtilsTest.scala

Provides a standard way to log the seed on test failure and to handle generation failure.

Add GenTestUtils

---

build.sbt

I was getting a 
```
No logging platforms found in while using google flogger logging ClassNotFoundException: com.google.common.flogger.backend.system.DefaultPlatform
```
error when running the tests locally in ratatool. It looks like we need to add a logging backend to ratatool in order to have flogger function properly. According to the flogger docs, https://github.com/google/flogger#1-add-the-dependencies-on-flogger, we need to add https://mvnrepository.com/artifact/com.google.flogger/flogger-system-backend/0.7.4 to build.sbt.
I set the scope to `test` in order to avoid adding dependencies for our users binary.

add flogger backend dependency

---

ratatool-sampling/src/main/scala/com/spotify/ratatool/samplers/BigSampler.scala
ratatool-sampling/src/test/scala/com/spotify/ratatool/samplers/BigSamplerTest.scala
scalastyle-config.xml

Below changes have been tested and confirmed to work. Also proposing alternative approach since I'm not a big fan of guessing whether we are dealing with Avro vs Parquet:
Approach (1)
- This PR, minimal change. Basically checking to see if the matching files has the relevant extensions and routing it to either `AvroSampler` or `ParquetSample`
Approach (2) 
- Not in this PR, but I think we should create a new arg called `mode` (which can be either `parquet`, `avro` or `bigquery`) and have that be a required field. It will be a breaking change, but then it will help avoid guessing which Sampler to use.

Fix filepath wildcard for avro/parquet

---

ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/BigDiffy.scala
ratatool-diffy/src/test/scala/com/spotify/ratatool/diffy/BigDiffyTest.scala

WHAT: Changing `mergeTableSchema` to support LHS as well as RHS schema, returning a schema containing all the fields of both schemas, and adding test for new functionality.
WHY: To make RHS schema be considered in `mergeTableSchema` when using bigdiffy in bigquery.
HOW: changes `val yMap = x.map(f => (f.getName, f)).toMap` to `val yMap = y.map(f => (f.getName, f)).toMap`

Change yMap and add test

---

ratatool-common/src/main/avro/TestRecord.avsc
ratatool-sampling/src/test/scala/com/spotify/ratatool/io/FixRandomData.scala
ratatool-scalacheck/src/main/scala/com/spotify/ratatool/scalacheck/AvroGenerator.scala
ratatool-scalacheck/src/test/scala/com/spotify/ratatool/scalacheck/AvroGeneratorTest.scala

Attempt to add support for logical decimal types to avroOf See issue #178
It appears the Builder still fails when nested records rely on Avro Conversions since it only includes them in the generated classes for the nested record, and not for the parent record builder.
I also could not get it to work for nullable logical decimal types as the type coercion fails for the null array (it's a bit related to the above issue that we'd want it to call the Conversion and also handle nulls - e.g. 0 byte array -> null).
Note I also don't handle the case of a fixed underlying byte array size in the Avro schema, nor checking that the generated integer will fit inside the decimal's precision and scale - but at the moment the above issues are more blocking.

Add logical decimal type support to avroOf

---

.scala-steward.conf
build.sbt

it seems good to match versions for dependencies we share with scio

downgrade some libs to match scio

---

build.sbt
ratatool-diffy/src/test/scala/com/spotify/ratatool/diffy/AvroDiffyTest.scala
ratatool-diffy/src/test/scala/com/spotify/ratatool/diffy/BigDiffyTest.scala
ratatool-examples/src/main/scala/com/spotify/ratatool/examples/diffy/PreProcessBigDiffy.scala
ratatool-examples/src/test/scala/com/spotify/ratatool/examples/PreProcessBigDiffyJobTest.scala
ratatool-scalacheck/src/main/scala/com/spotify/ratatool/scalacheck/AvroGenerator.scala
ratatool-scalacheck/src/test/scala/com/spotify/ratatool/scalacheck/AvroGeneratorTest.scala

This is not ideal, but force the avro coder to use the reflect API so `CharSequence` implementation is `String`.
When it is `Utf8`, `AvroDiffy` implementation emits Delta of distance zero

Update scio to 0.13.6

---

ratatool-sampling/README.md
ratatool-sampling/src/main/scala/com/spotify/ratatool/samplers/BigSampler.scala
ratatool-sampling/src/main/scala/com/spotify/ratatool/samplers/BigSamplerBigQuery.scala

adds a new arg to BigSampler called `bigqueryPartitioning`, defaults to "DAY", which should maintain the same behavior as before. Users can pass in "DAY|HOUR|MONTH|YEAR", as well as NULL if no table partitioning is desired. 
Making this change so that Ratatool works better with Spotify's internal Luigi BigQuery tasks, which use table sharding as partitioning, and when ratatool sets the partitioning to ingestion day, it causes problems with retention.
Tested by outputting [this](https://console.cloud.google.com/bigquery?project=data-quality-spotify&ws=!1m5!1m4!4m3!1sdata-quality-spotify!2sbenk_test_eu!3sbenk_test_eu_20240219) table via this workflow:
```
apiVersion: workflow.data.spotify.com/v1alpha1
kind: Workflow
metadata:
name: ratatool-internal-examples-stream-days-bigsampler …
```

make bigsampler bq output partition configurable

---

build.sbt
ratatool-sampling/src/main/scala/com/spotify/ratatool/samplers/BigSampler.scala
ratatool-scalacheck/src/main/scala/com/spotify/ratatool/scalacheck/ProtoBufGenerator.scala
ratatool-scalacheck/src/main/scala/com/spotify/ratatool/scalacheck/TableRowGenerator.scala

Fix #46
Do not couple `ratatool-sampling` to any runner implementation

Cleanup beam dependencies

---

ratatool-sampling/src/main/scala/com/spotify/ratatool/samplers/BigSampler.scala

Do not import class that may be missing from user's classpath
Compute key size using machine memory instead of CPUs

Decouple dataflow in ratatool-scalacheck

---

ratatool-scalacheck/src/main/scala/com/spotify/ratatool/scalacheck/AvroGenerator.scala
ratatool-scalacheck/src/main/scala/com/spotify/ratatool/scalacheck/HashMapBuildable.scala
ratatool-scalacheck/src/test/scala/com/spotify/ratatool/scalacheck/AvroGeneratorTest.scala

Attempt to support `java-class` and `java-key-class` as defined in the avro [specification](https://avro.apache.org/docs/1.11.1/api/java/)
`java-element-class` is only used in the reflect API

Support java-class stringable property
