spotify/ratatool

.travis.yml
build.sbt
project/plugins.sbt

Upgrade Scala to 2.12.4 and upgrade dependencies

---

build.sbt

update release settings for sonatype

---

README.md

Fix redirected links in README, add note re running BigDiffy via CLI

---

build.sbt
ratatool-sampling/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java
ratatool-scalacheck/src/main/scala/com/spotify/ratatool/scalacheck/package.scala

Bump Scio to 0.5.0

---

build.sbt

Breaking change not accommodated for in scio upgrade

Add scio-runners as dependencies for diffy and sampler

---

ratatool-sampling/src/main/scala/com/spotify/ratatool/samplers/BigSampler.scala

Force FileSystems to load/register service classes

---

build.sbt
ratatool-sampling/src/main/scala/com/spotify/ratatool/samplers/BigSampler.scala

Guava version bump, Plugin cleanup

---

ratatool-scalacheck/src/main/scala/com/spotify/ratatool/scalacheck/AvroGenerator.scala

Add avroOf aliases for API consistency

---

build.sbt

Remove Guava dep entirely

---

ratatool-scalacheck/src/main/scala/com/spotify/ratatool/scalacheck/package.scala
ratatool-scalacheck/src/test/scala/com/spotify/ratatool/scalacheck/ProtoBufGeneratorTest.scala

#62 , requires pre-converting to a builder and then building again at the end instead of converting and rebuilding for every instance of every field

`.amend()` for Protobuf

---

README.md

README should point to other dirs with READMEs

---

ratatool-sampling/README.md
ratatool-sampling/src/main/scala/com/spotify/ratatool/samplers/BigSampler.scala
ratatool-sampling/src/test/scala/com/spotify/ratatool/samplers/BigSamplerTest.scala

Addresses #24 
Not sure if more communication around this potentially being a breaking change is necessary

replace murmur hash with farmhash

---

build.sbt
ratatool-examples/src/main/avro/schema.avsc
ratatool-examples/src/main/scala/com/spotify/ratatool/examples/diffy/PreProcessBigDiffy.scala
ratatool-examples/src/test/scala/com/spotify/ratatool/examples/PreProcessBigDiffyJobTest.scala

Pre-processing example for BigDiffy

---

ratatool-common/src/main/avro/TestRecord.avsc
ratatool-sampling/src/main/scala/com/spotify/ratatool/samplers/BigSampler.scala
ratatool-sampling/src/main/scala/com/spotify/ratatool/samplers/BigSamplerAvro.scala
ratatool-sampling/src/test/scala/com/spotify/ratatool/samplers/BigSamplerTest.scala

* Adds a unit test for all currently supported avro types.
* Makes bytes and fixed consistent with hex strings.
* Fixes incorrect casting for byte and enum types.

Adds support for fixed type.

---

.travis.yml

Hopefully this will fix Travis build without having to add a lot of other things like I was trying in https://github.com/spotify/ratatool/pull/163

Only switch Oracle JDK to Open JDK

---

ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/AvroDiffy.scala
ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/BigDiffy.scala
ratatool-sampling/src/main/scala/com/spotify/ratatool/samplers/BigSamplerAvro.scala

Specify coders for generic records

---

.circleci/config.yml
build.sbt

Also should we add this repo to scala-steward?

bump versions

---

ratatool-sampling/src/test/scala/com/spotify/ratatool/samplers/BigSamplerTest.scala

Widen bounds of flaky sampling test

---

ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/AvroDiffy.scala

Fix check for nested repeated records

---

ratatool-diffy/README.md

taken from here https://github.com/spotify/ratatool/blob/master/ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/BigDiffy.scala#L423

update cli args

---

ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/BigDiffy.scala
ratatool-diffy/src/test/scala/com/spotify/ratatool/diffy/BigDiffyTest.scala

BigDiffy was inferring the wrong coder resulting in errors when NaN values were passed. This PR is explicitly defining the coder

making coder explicit for row comparisons

---

catalog.yaml

registering ownership of ratatool oss to blizzard

added catalog.yaml

---

ratatool-diffy/README.md

https://spotify.slack.com/archives/C047H3XMT/p1691499040962629

clarify unique key requirement

---

ratatool-scalacheck/src/test/scala/com/spotify/ratatool/scalacheck/AvroGeneratorTest.scala

Add unit-test for avro logical type generator
